# Generated by Django 3.2.12 on 2022-09-15 11:01

import payments.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_auto_20200821_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="details",
            field=payments.utils.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="payment",
            name="extra",
            field=payments.utils.JSONField(blank=True, default=dict),
        ),
    ]
