# Generated by Django 5.0.4 on 2024-10-22 09:06

import django_countries.fields
import vies.models
from django.db import migrations, models

import wlhosted.payments.validators


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0025_alter_payment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(default="", max_length=200, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                default="", max_length=200, verbose_name="Postcode and city"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=django_countries.fields.CountryField(
                default="", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Company or individual name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="vat",
            field=vies.models.VATINField(
                blank=True,
                default="",
                help_text="Please fill in European Union VAT ID, leave blank if not applicable.",
                max_length=14,
                validators=[wlhosted.payments.validators.validate_vatin],
                verbose_name="European VAT ID",
            ),
        ),
    ]
