# Generated by Django 5.0.4 on 2024-10-25 08:36

import weblate.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0026_alter_customer_address_alter_customer_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Additional address information",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode",
            field=models.CharField(default="", max_length=20, verbose_name="Postcode"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=190,
                validators=[weblate.utils.validators.EmailValidator()],
            ),
        ),
    ]
