# Generated by Django 5.1.6 on 2025-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0028_customer_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="end_client",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="End client name"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
    ]
