# Generated by Django 5.2.1 on 2025-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0029_customer_end_client_customer_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="zammad_id",
            field=models.IntegerField(default=0),
        ),
    ]
