# Generated by Django 5.2.1 on 2025-07-28 09:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0030_customer_zammad_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
