# Generated by Django 6.0.3 on 2026-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0031_alter_payment_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="upcoming_payment_notification_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
