# Generated by Django 6.0.4 on 2026-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0032_customer_upcoming_payment_notification_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
