# Generated by Django 6.0.5 on 2026-05-20 08:03

import django.core.serializers.json
import django.db.models.deletion
import vies.models
from django.db import migrations, models

import wlhosted.payments.validators


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0033_alter_customer_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="vat_validated",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="vat_validation_error",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="vat_validation_state",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="card_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="customer",
            name="vat",
            field=vies.models.VATINField(
                blank=True,
                default="",
                help_text="Please fill in European Union VAT ID, leave blank if not applicable.",
                max_length=14,
                null=True,
                validators=[wlhosted.payments.validators.validate_vatin],
                verbose_name="European VAT ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.IntegerField(
                choices=[(0, "EUR"), (1, "BTC"), (2, "USD"), (3, "CZK"), (4, "GBP")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="payments.customer"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="repeat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.payment",
            ),
        ),
    ]
