# Generated by Django 6.0.5 on 2026-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0035_fill_billing_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="vat_validation_state",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
