# Generated by Django 6.0.5 on 2026-07-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0036_alter_customer_vat_validation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accounting_reference",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_point",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
