# Generated by Django 6.0.5 on 2026-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0037_customer_accounting_reference_customer_contact_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="follow_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="follow_up_note",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
