# Generated by Django 6.0.5 on 2026-07-09 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0038_customer_follow_up_at_customer_follow_up_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="follow_up_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="follow_up_note",
        ),
    ]
