name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
        - '3.12'
        - '3.13'
        - '3.14'
    name: Python ${{ matrix.python-version }}

    services:
      redis:
        image: redis:8.8.0-alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
        ports:
        - 6379:6379
      postgres:
        image: postgres:18.4-alpine@sha256:1b1689b20d16a014a3d195653381cf2caa75a41a92d93b255a9d6ea29fd353aa
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Configure git
      run: |
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Job"
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install libcairo-dev gir1.2-pango-1.0 libgirepository-2.0-dev libacl1-dev gettext liblz4-dev libzstd-dev libxxhash-dev gir1.2-rsvg-2.0 libleptonica-dev libtesseract-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        cache-suffix: test-${{ matrix.python-version }}
        version: 0.11.21
    - name: Install pip dependencies
      run: |
        uv sync --dev
        uv pip install https://github.com/WeblateOrg/weblate/archive/main.zip
    - name: Test with Django
      env:
        CI_DATABASE: postgresql
        CI_DB_PASSWORD: postgres
        CI_DB_HOST: localhost
        DJANGO_SETTINGS_MODULE: wlhosted.settings_test
      run: |
        uv run --no-sync weblate collectstatic --noinput
        uv run --no-sync pytest
    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} # zizmor: ignore[secrets-outside-env]
        flags: unittests
        name: Python ${{ matrix.python-version }}
permissions:
  contents: read
