name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
        - '3.12'
        - '3.13'
        - '3.14'
    name: Python ${{ matrix.python-version }}

    services:
      redis:
        image: redis:8.6.2-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
        ports:
        - 6379:6379
      postgres:
        image: postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Configure git
      run: |
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Job"
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install libcairo-dev gir1.2-pango-1.0 libgirepository-2.0-dev libacl1-dev gettext liblz4-dev libzstd-dev libxxhash-dev gir1.2-rsvg-2.0 libleptonica-dev libtesseract-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      with:
        cache-suffix: test-${{ matrix.python-version }}
        version: 0.11.2
    - name: Install pip dependencies
      run: |
        uv sync --dev
        uv pip install https://github.com/WeblateOrg/weblate/archive/main.zip
    - name: Test with Django
      env:
        CI_DATABASE: postgresql
        CI_DB_PASSWORD: postgres
        CI_DB_HOST: localhost
        DJANGO_SETTINGS_MODULE: wlhosted.settings_test
      run: |
        uv run --no-sync weblate collectstatic --noinput
        uv run --no-sync pytest
    - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}} # zizmor: ignore[secrets-outside-env]
        flags: unittests
        name: Python ${{ matrix.python-version }}
permissions:
  contents: read
